#!/usr/bin/expect -f

set user [lindex $argv 0]
set pass [lindex $argv 1]
set totp [lindex $argv 2]

spawn openvpn --config profile.ovpn --user nobody
expect "Enter Auth Username:"
send $user
send "\n"
expect "Enter Auth Password:"
send $pass
send "\n"
expect "CHALLENGE: Enter Google Authenticator Code"
send $totp
send "\n"
interact
